### ISSUE TITLE
Should_Return_MarketSymbols_From_Sample_Archive_File failing .net45

### ISSUE THREAD

**Issue by mathpaquette** [mathpaquette/IQFeed.CSharpApiClient#10]
System.Net.WebException : The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at IQFeed.CSharpApiClient.Lookup.Symbol.MarketSymbols.MarketSymbolDownloader.GetMarketSymbolsFile(String downloadPath, String marketSymbolsUrl)
   at IQFeed.CSharpApiClient.Lookup.Symbol.SymbolFacade.GetAllMarketSymbols(String downloadPath, String marketSymbolsArchiveUrl)
   at IQFeed.CSharpApiClient.Tests.Integration.Lookup.Symbol.SymbolFacadeTests.Should_Return_MarketSymbols_From_Sample_Archive_File()

**Comment by mathpaquette** [comment]
The issue still persist on Framework 4.5.....

**Comment by mathpaquette** [comment]
@license786 can you please put the screenshot here.

**Comment by Nucs** [comment]
If the ssl issue still persists,  Please try this answer and let us know the results. 
https://stackoverflow.com/a/48930280

Regarding the problem with `ZipFile`, @mathpaquette, we'll need to add nuget reference to `System.Compression` because it has issues in NET45 (only to this framework). 
See: https://stackoverflow.com/a/48431402

**Comment by mathpaquette** [comment]
@Nucs the weird thing about the compression, @license786 targeting 4.6.1.... on my side it runs flawlessly

**Comment by license786** [comment]
What is the solution, i should try for now.

**Comment by mathpaquette** [comment]
@Nucs on his computer, I had to uninstall the IQFeed.Client change the target to NET4.5 reinstall to fix the issue.
